CREATE TABLE IF NOT EXISTS roles (
  roleId INT AUTO_INCREMENT PRIMARY KEY,
  roleName VARCHAR(100) NOT NULL,
  description VARCHAR(255),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS permissions (
  permissionId INT AUTO_INCREMENT PRIMARY KEY,
  permissionName VARCHAR(150) NOT NULL,
  permissionCode VARCHAR(100) NOT NULL,
  componentId INT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS role_permissions (
  rolePermissionId INT AUTO_INCREMENT PRIMARY KEY,
  roleId INT NOT NULL,
  permissionId INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (roleId) REFERENCES roles(roleId) ON DELETE CASCADE,
  FOREIGN KEY (permissionId) REFERENCES permissions(permissionId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS positions (
  positionId INT AUTO_INCREMENT PRIMARY KEY,
  positionName VARCHAR(100) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS departments (
  departmentId INT AUTO_INCREMENT PRIMARY KEY,
  departmentName VARCHAR(120) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sectors (
  sectorId INT AUTO_INCREMENT PRIMARY KEY,
  sectorName VARCHAR(120) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS establishment_types (
  establishmentTypeId INT AUTO_INCREMENT PRIMARY KEY,
  establishmentTypeName VARCHAR(120) NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  userId INT AUTO_INCREMENT PRIMARY KEY,
  firstName VARCHAR(120) NOT NULL,
  lastName VARCHAR(120) NOT NULL,
  userName VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL,
  password VARCHAR(255),
  contact VARCHAR(20),
  roleId INT,
  departmentId INT,
  positionId INT,
  sectorId INT,
  address VARCHAR(255),
  status TINYINT DEFAULT 1,
  establishmentName VARCHAR(150),
  establishmentTypeId INT,
  adharNo VARCHAR(50),
  adharCard VARCHAR(255),
  panNo VARCHAR(20),
  pan VARCHAR(255),
  city VARCHAR(120),
  pincode VARCHAR(12),
  state VARCHAR(120),
  alternatePhone VARCHAR(20),
  shopAct VARCHAR(255),
  accName VARCHAR(150),
  accNo VARCHAR(40),
  bankName VARCHAR(120),
  branch VARCHAR(120),
  ifsc VARCHAR(20),
  cheque VARCHAR(255),
  logo VARCHAR(255),
  gender VARCHAR(20),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (roleId) REFERENCES roles(roleId),
  FOREIGN KEY (departmentId) REFERENCES departments(departmentId),
  FOREIGN KEY (positionId) REFERENCES positions(positionId),
  FOREIGN KEY (sectorId) REFERENCES sectors(sectorId),
  FOREIGN KEY (establishmentTypeId) REFERENCES establishment_types(establishmentTypeId)
);

CREATE TABLE IF NOT EXISTS teams (
  teamId INT AUTO_INCREMENT PRIMARY KEY,
  teamName VARCHAR(150) NOT NULL,
  teamLeadId INT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (teamLeadId) REFERENCES users(userId)
);

CREATE TABLE IF NOT EXISTS team_members (
  teamMemberId INT AUTO_INCREMENT PRIMARY KEY,
  teamId INT NOT NULL,
  userId INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (teamId) REFERENCES teams(teamId) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES users(userId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sales_targets (
  salesTargetId INT AUTO_INCREMENT PRIMARY KEY,
  teamId INT NOT NULL,
  targetMonth DATE NOT NULL,
  targetAmount DECIMAL(12,2) DEFAULT 0,
  achievedAmount DECIMAL(12,2) DEFAULT 0,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (teamId) REFERENCES teams(teamId) ON DELETE CASCADE
);
