CREATE TABLE IF NOT EXISTS tour_fixtures (
  fixtureKey VARCHAR(100) NOT NULL PRIMARY KEY,
  fixtureValue JSON NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
