CREATE TABLE IF NOT EXISTS tours (
  tourId INT AUTO_INCREMENT PRIMARY KEY,
  tourCode VARCHAR(30) NOT NULL UNIQUE,
  tourName VARCHAR(200) NOT NULL,
  tourType ENUM('GROUP','CUSTOM') NOT NULL DEFAULT 'GROUP',
  status ENUM('DRAFT','PUBLISHED','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
  startDate DATE,
  endDate DATE,
  basePrice DECIMAL(12,2),
  capacity INT,
  publishedAt DATETIME,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS enquiries (
  enquiryId INT AUTO_INCREMENT PRIMARY KEY,
  enquiryCode VARCHAR(30) NOT NULL UNIQUE,
  tourId INT,
  enquiryType ENUM('GROUP','CUSTOM') NOT NULL DEFAULT 'GROUP',
  customerName VARCHAR(150) NOT NULL,
  contact VARCHAR(50),
  email VARCHAR(150),
  noOfGuests INT,
  travelDate DATE,
  status ENUM('NEW','FOLLOW_UP','CONFIRMED','LOST') NOT NULL DEFAULT 'NEW',
  workflowStage ENUM('ENQUIRY','FOLLOW_UP','CONFIRMED','BOOKED','LOST') NOT NULL DEFAULT 'ENQUIRY',
  assignedUserId INT,
  sourcePage VARCHAR(100),
  notes TEXT,
  lastFollowUpAt DATETIME,
  nextFollowUpAt DATETIME,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tourId) REFERENCES tours(tourId) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS enquiry_followups (
  followupId INT AUTO_INCREMENT PRIMARY KEY,
  enquiryId INT NOT NULL,
  previousStatus ENUM('NEW','FOLLOW_UP','CONFIRMED','LOST'),
  newStatus ENUM('NEW','FOLLOW_UP','CONFIRMED','LOST') NOT NULL,
  remarks TEXT,
  nextActionDate DATE,
  actionBy INT,
  actionAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (enquiryId) REFERENCES enquiries(enquiryId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
  bookingId INT AUTO_INCREMENT PRIMARY KEY,
  bookingCode VARCHAR(30) NOT NULL UNIQUE,
  enquiryId INT NOT NULL,
  tourId INT,
  bookingDate DATE NOT NULL,
  totalAmount DECIMAL(12,2),
  amountPaid DECIMAL(12,2),
  status ENUM('PENDING','CONFIRMED','COMPLETED','CANCELLED') NOT NULL DEFAULT 'PENDING',
  notes TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (enquiryId) REFERENCES enquiries(enquiryId) ON DELETE CASCADE,
  FOREIGN KEY (tourId) REFERENCES tours(tourId) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS guest_records (
  guestId INT AUTO_INCREMENT PRIMARY KEY,
  bookingId INT NOT NULL,
  fullName VARCHAR(150) NOT NULL,
  passportNo VARCHAR(50),
  documentStatus ENUM('PENDING','RECEIVED','VERIFIED') NOT NULL DEFAULT 'PENDING',
  roomType VARCHAR(50),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (bookingId) REFERENCES bookings(bookingId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS operation_tasks (
  taskId INT AUTO_INCREMENT PRIMARY KEY,
  bookingId INT NOT NULL,
  taskType ENUM('HOTEL','TRANSPORT','GUIDE','OTHER') NOT NULL DEFAULT 'OTHER',
  description TEXT,
  status ENUM('PENDING','IN_PROGRESS','DONE') NOT NULL DEFAULT 'PENDING',
  dueDate DATE,
  assignedTo INT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (bookingId) REFERENCES bookings(bookingId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS billing_records (
  billingId INT AUTO_INCREMENT PRIMARY KEY,
  bookingId INT NOT NULL,
  invoiceNumber VARCHAR(50) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  dueDate DATE,
  paidDate DATE,
  status ENUM('PENDING','PAID','OVERDUE') NOT NULL DEFAULT 'PENDING',
  notes TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (bookingId) REFERENCES bookings(bookingId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS feedback_records (
  feedbackId INT AUTO_INCREMENT PRIMARY KEY,
  bookingId INT NOT NULL,
  rating TINYINT,
  feedback TEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (bookingId) REFERENCES bookings(bookingId) ON DELETE CASCADE
);
