const { Router } = require("express");
const tourController = require("../controllers/tourController");
const uploadMiddleware = require("../middleware/upload");

const router = Router();

router.post(
  "/add-tour-details",
  uploadMiddleware.fields([
    { name: "bgImage", maxCount: 1 },
    { name: "websiteBanner", maxCount: 1 },
  ]),
  tourController.createGroupTour
);
router.post("/add-group-tour-info", tourController.addGroupTourInfo);
router.post("/add-skeleton-details", tourController.addSkeletonDetails);
router.post("/add-group-tour-price", tourController.addGroupTourPrice);
router.post("/add-travel-details", tourController.addTravelDetails);
router.post("/add-detail-itinerary", tourController.addDetailItinerary);
router.get("/group-tour-dropdown", tourController.listGroupTourDropdown);
router.get("/priority-list", tourController.listPriorityList);
router.get("/enqGroup-details", tourController.getGroupEnquiryDetails);
router.get("/booking-records", tourController.listGroupBookingRecords);
router.get("/all-booking-records-gt", tourController.listAllGroupBookingRecords);
router.get("/booking-record-ct", tourController.listCustomBookingRecords);
router.get("/all-booking-records-ct", tourController.listAllCustomBookingRecords);
router.get("/family-head-data", tourController.listFamilyHeadData);
router.get("/familyHead-list-gt", tourController.listFamilyHeadData);
router.get("/get-enquiry-familyHeadGt", tourController.getEnquiryFamilyHead);
router.get("/room-share-family-haed-gt", tourController.listFamilyHeadRoomShare);
router.get("/dropdownRoomPrice", tourController.listRoomPriceDropdown);
router.get("/dropdowbTravelMode", tourController.listTravelModeDropdown);
router.get("/guests-list-group-tour", tourController.listGroupGuestsForCancellation);
router.get("/billing/guests-list-group-tour", tourController.listGroupGuestsForCancellation);
router.get("/get-cancellation-process-data", tourController.getGroupCancellationProcessData);
router.get("/get-guest-details-gt", tourController.getGuestDetailsGt);
router.get("/guests-document-gt", tourController.listGuestDocuments);
router.get("/get-tour-cost-gt", tourController.getTourCostGt);
router.get("/get-coupon-uses-gt", tourController.getCouponUsage);
router.get("/exists-user", tourController.checkGuestExists);
router.get("/payment-mode-list", tourController.listPaymentModeOptions);
router.get("/online-type-list", tourController.listOnlineTypeOptions);
router.get("/card-type-list", tourController.listCardTypeOptions);
router.get("/get-payment-calculation-gt", tourController.getPaymentCalculation);
router.get("/view-payment-bill-gt", tourController.getGroupPaymentBill);
router.get("/view-bill-group-tour", tourController.getGroupBillView);
router.get("/group-tour-completion-status", tourController.getGroupTourCompletionStatus);
router.get("/total-call-count-gt", tourController.getGroupTotalCallCount);
router.get("/dropdown-call-status", tourController.listCallStatusDropdown);
router.get("/call-follow-history-gt", tourController.listCallFollowHistory);
router.get("/confirm-group-tour-list", tourController.listConfirmGroupTours);
router.get("/all-confirm-group-tour-list", tourController.listAllConfirmGroupTours);
router.get("/confirm-custom-list", tourController.listConfirmCustomTours);
router.get("/all-confirm-custom-list", tourController.listAllConfirmCustomTours);
router.get("/guest-detail-gt-list", tourController.listGroupGuestDetails);
router.get("/all-guest-detail-gt-list", tourController.listAllGroupGuestDetails);
router.get("/guest-detail-ct-list", tourController.listCustomGuestDetails);
router.get("/all-guest-detail-ct-list", tourController.listAllCustomGuestDetails);
router.get("/plan-enq-users-list-gt", tourController.listPlanEnquiryUsersGt);
router.get("/plan-enq-users-list-ct", tourController.listPlanEnquiryUsersCt);
router.get("/future-enquiry-all-listing", tourController.listFutureEnquiryAll);
router.get("/future-enquiry-self-listing", tourController.listFutureEnquirySelf);
router.get("/paypending-list", tourController.listPendingGroupPayments);
router.get("/pending-pay-list-ct", tourController.listPendingCustomPayments);
router.get("/confirm-pay-list-ct", tourController.listConfirmedCustomPayments);
router.get("/lost-enquiry-group-tour", tourController.listLostGroupEnquiries);
router.get("/lost-enquiry-custom", tourController.listLostCustomEnquiries);
router.get("/all-lost-enqs-gt", tourController.listAllLostGroupEnquiries);
router.get("/all-lost-enqs-ct", tourController.listAllLostCustomEnquiries);
router.get("/dd-prefix", tourController.listPrefixDropdown);
router.get("/dropdown-guest-refId", tourController.listGuestReferenceDropdown);
router.get("/enquiry-reference-list", tourController.listEnquiryReferenceDropdown);
router.get("/list-group-tour", tourController.listMyGroupFollowUps);
router.get("/expired-list-group-tour", tourController.listMyExpiredGroupFollowUps);
router.get("/upcoming-list-group-tour", tourController.listMyUpcomingGroupFollowUps);
router.get("/all-enquiry-today-list-gt", tourController.listAllGroupTodayFollowUps);
router.get("/all-enquiry-expired-list-gt", tourController.listAllGroupExpiredFollowUps);
router.get("/all-enquiry-upcoming-list-gt", tourController.listAllGroupUpcomingFollowUps);
router.get("/billing/enquiry-follow-custom", tourController.listMyCustomFollowUps);
router.get("/expired-enquiry-follow-CT", tourController.listMyExpiredCustomFollowUps);
router.get("/upcoming-enquiry-follow-CT", tourController.listMyUpcomingCustomFollowUps);
router.get("/assigned-custom-tour-list", tourController.listAssignedCustomTodayFollowUps);
router.get("/assigned-expired-custom-tour-list", tourController.listAssignedCustomExpiredFollowUps);
router.get("/assigned-upcoming-custom-tour-list", tourController.listAssignedCustomUpcomingFollowUps);
router.get("/assigned-all-custom-tour-list", tourController.listAssignedAllCustomTodayFollowUps);
router.get("/assigned-all-expired-custom-tour-list", tourController.listAssignedAllCustomExpiredFollowUps);
router.get("/assigned-all-upcoming-custom-tour-list", tourController.listAssignedAllCustomUpcomingFollowUps);
router.get("/all-enq-today-ct", tourController.listAllCustomTodayFollowUps);
router.get("/all-enq-expired-ct", tourController.listAllCustomExpiredFollowUps);
router.get("/all-enq-upcoming-ct", tourController.listAllCustomUpcomingFollowUps);
router.get("/view-group-tour", tourController.listGroupTours);
router.get("/view-draft-group-tour", tourController.listDraftGroupTours);
router.get("/view-tailor-made", tourController.listTailorMadeTours);
router.get("/view-custom-tour", tourController.listCustomTours);
router.get("/tour-type-list", tourController.listTourTypes);
router.get("/city-list", tourController.listCities);
router.get("/destination-list", tourController.listDestinations);
router.get("/vehicle-listing", tourController.listVehicles);
router.get("/meal-plan-list", tourController.listMealPlans);
router.get("/meal-type-list", tourController.listMealTypes);
router.get("/kitchen-list", tourController.listKitchens);
router.get("/departure-type-list", tourController.listDepartureTypes);
router.get("/country", tourController.listCountries);
router.get("/enquiry-ct", tourController.getCustomizedEnquiryDetails);
router.get("/get-enquiry-ct", tourController.getCustomizedEnquiryDetails);
router.get("/package-list", tourController.listCustomizedPackages);
router.get("/guests-group-tour", tourController.listGroupTourGuests);
router.get("/view-details-group-tour", tourController.getGroupTourViewDetails);
router.get("/view-details-tailor-made", tourController.getTailorMadeTourViewDetails);
router.get("/get-edit-tailor-made", tourController.getTailorMadeTourDetails);
router.post("/update-tailor-made-list", tourController.updateTailorMadeTour);
router.get("/edit-data-gt", tourController.getGroupTourDetails);

module.exports = router;
