const express = require("express");
const router = express.Router();
const billingController = require("../controllers/admin/billController");

router.get("/total-billing", billingController.totalBilling);
router.get("/total-bill-approved", billingController.totalBillApproved);
router.get("/total-bill-pending", billingController.totalBillPending);
router.get("/profit-ct", billingController.profitCt);

router.get("/booking-sales-amount-graph-ct", billingController.bookingSalesAmountGraphCt);
router.get("/list-sales-profit", billingController.listSalesProfit);
router.get("/no-of-guests", billingController.noOfGuests);
router.get("/group-tour-count", billingController.groupTourCount);
router.get("/top-sales-partner", billingController.topSalesPartner);
router.get("/enquiry-list-ct", billingController.enquiryListCt);
router.get("/enquiry-graph-ct", billingController.enquiryGraphCt);
router.get("/target-ct", billingController.targetCt);
router.get("/monthly-target-graph-ct", billingController.monthlyTargetGraphCt);
router.get("/enquiry-list-gt", billingController.enquiryListGt);
router.get("/enquiry-graph-gt", billingController.enquiryGraphGt);
router.get("/target-gt", billingController.targetGt);
router.get("/welcome-booking", billingController.welcomeBooking);
router.get("/birthday-lists", billingController.birthdayLists);
router.get("/monthly-target-graph-gt", billingController.monthlyTargetGraphGt);
router.get("/guests-list-group-tour", billingController.guestsListGroupTour);
router.get("/loyalty-booking", billingController.loyaltyBooking);
router.get("/enquiry-follow-custom", billingController.enquiryFollowCustomTourList);
router.get("/referral-rate", billingController.referralRate);
router.get("/more-booking-count", billingController.moreBookingCount);
module.exports = router;
